import { ensureEnv } from '@take-out/helpers'

if (typeof window !== 'undefined') {
  throw new Error(`This is a server-only file`)
}

// 🔒 start - this is generated by "bun env:update"
export const ONE_SERVER_URL = ensureEnv('ONE_SERVER_URL')
export const VITE_WEB_HOSTNAME = ensureEnv('VITE_WEB_HOSTNAME', "")
export const VITE_CREATON_FORUM_APPVIEW_URL = ensureEnv('VITE_CREATON_FORUM_APPVIEW_URL', "")
export const VITE_CREATON_INTROSPECT_URL = ensureEnv('VITE_CREATON_INTROSPECT_URL', "")
// 🔒 end - this is generated by "bun env:update"

// database urls set conditionally based on deployment
// use bracket notation to prevent build-time inlining
export const ZERO_UPSTREAM_DB = process.env['ZERO_UPSTREAM_DB'] || ''
export const ZERO_CVR_DB = process.env['ZERO_CVR_DB'] || ''
export const ZERO_CHANGE_DB = process.env['ZERO_CHANGE_DB'] || ''
