use std::collections::BTreeMap;
use std::num::{NonZeroU32, NonZeroUsize};

use commonware_codec::{Encode, Read};
use commonware_cryptography::bls12381::{
    dkg::golden::{self, DealerLog, Info, Output, PrivateKey, PublicKey, Setup, SignedDealerLog},
    primitives::{group::Share, sharing::ModeVersion},
};
use commonware_math::algebra::Random;
use commonware_parallel::Rayon;
use commonware_utils::{ordered::Set, Faults, TryCollect};
use num_traits::ToPrimitive;
use rand_core::CryptoRngCore;
use sha2::{Digest, Sha256};
use thiserror::Error;

pub const DKG_NAMESPACE: &[u8] = b"app.creaton.forum.dkg-service.v1";

#[derive(Debug, Error)]
pub enum DkgError {
    #[error("participant count {0} is outside supported range")]
    InvalidParticipantCount(usize),
    #[error("threshold {threshold} is invalid for {participants} participants")]
    InvalidThreshold { threshold: usize, participants: usize },
    #[error("duplicate participant identities")]
    DuplicateParticipants,
    #[error("failed to decode setup: {0}")]
    InvalidSetup(String),
    #[error("failed to decode output: {0}")]
    InvalidOutput(String),
    #[error("failed to decode share: {0}")]
    InvalidShare(String),
    #[error("failed to decode dealer log: {0}")]
    InvalidDealerLog(String),
    #[error("DKG protocol error: {0}")]
    Protocol(String),
    #[error("insufficient dealer logs: got {got}, need {need}")]
    InsufficientDealerLogs { got: usize, need: usize },
}

/// Generic `Faults` profile parameterized by the maximum number of faults.
///
/// Commonware Golden uses `n - max_faults` as the quorum/threshold.
/// We ignore `n` because the caller already validated it against the participant set.
pub struct MaxFaults<const F: u32>;

impl<const F: u32> Faults for MaxFaults<F> {
    fn max_faults(_n: impl ToPrimitive) -> u32 {
        F
    }
}

/// Reusable public setup for Commonware Golden.
///
/// Contains no private key material and can be distributed to every node.
#[derive(Clone)]
pub struct GoldenSetup {
    setup: std::sync::Arc<Setup>,
    max_players: NonZeroU32,
}

impl std::fmt::Debug for GoldenSetup {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GoldenSetup")
            .field("max_players", &self.max_players)
            .finish_non_exhaustive()
    }
}

impl GoldenSetup {
    pub fn generate(max_players: NonZeroU32) -> Self {
        Self {
            setup: std::sync::Arc::new(Setup::new(max_players)),
            max_players,
        }
    }

    pub fn encode(&self) -> Vec<u8> {
        self.setup.encode().to_vec()
    }

    pub fn decode(encoded: &[u8], max_players: NonZeroU32) -> Result<Self, DkgError> {
        let mut bytes = encoded;
        let setup = Setup::read_cfg(&mut bytes, &max_players)
            .map_err(|error| DkgError::InvalidSetup(error.to_string()))?;
        if !bytes.is_empty() {
            return Err(DkgError::InvalidSetup("trailing setup bytes".into()));
        }
        Ok(Self {
            setup: std::sync::Arc::new(setup),
            max_players,
        })
    }

    pub fn max_players(&self) -> NonZeroU32 {
        self.max_players
    }
}

/// Result of a local Golden DKG round.
#[derive(Clone, Debug)]
pub struct DkgResult {
    pub public_output: Output<PublicKey>,
    pub public_output_bytes: Vec<u8>,
    pub public_key: commonware_cryptography::bls12381::primitives::group::G1,
    pub transcript_hash: [u8; 32],
    /// Share for each participant, keyed by the caller-provided participant id.
    pub shares: Vec<(String, Share)>,
}

/// Caller-supplied description of a board member.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct ParticipantSpec {
    pub id: String,
    /// Opaque public key provided by the caller for audit purposes.
    /// In the local simulation the cryptographic identity is generated by the service.
    #[serde(rename = "publicKey")]
    pub public_key: String,
}

/// Generate a fresh BLS identity to use as a local Golden participant.
pub fn generate_identity(rng: &mut impl CryptoRngCore) -> PrivateKey {
    PrivateKey::random(rng)
}

/// Run a complete Commonware Golden DKG round locally for the supplied participants.
///
/// Each caller-supplied participant is assigned a freshly generated BLS identity for the
/// simulation. The service stores every share, so it can later issue partial decryptions on
/// behalf of any board member.
///
/// `previous` is reserved for future proactive resharing that preserves the public key
/// across epochs; it is currently ignored because a local reshare regenerates fresh
/// identities for the new participant set.
pub fn run_dkg(
    setup: &GoldenSetup,
    epoch: u64,
    participants: &[ParticipantSpec],
    threshold: u32,
    _previous: Option<&Output<PublicKey>>,
    rng: &mut impl CryptoRngCore,
) -> Result<DkgResult, DkgError> {
    let n = participants.len();
    if n == 0 || n > 64 {
        return Err(DkgError::InvalidParticipantCount(n));
    }
    let threshold_usize = threshold as usize;
    if threshold_usize == 0 || threshold_usize > n {
        return Err(DkgError::InvalidThreshold {
            threshold: threshold_usize,
            participants: n,
        });
    }

    let max_faults = n - threshold_usize;

    // Generate one local BLS identity per participant.
    let identities: Vec<_> = (0..n).map(|_| generate_identity(rng)).collect();
    let public_keys: Vec<PublicKey> = identities.iter().map(PrivateKey::public).collect();

    let dealers: Set<PublicKey> = public_keys
        .iter()
        .cloned()
        .try_collect()
        .map_err(|_| DkgError::DuplicateParticipants)?;
    let players: Set<PublicKey> = public_keys
        .into_iter()
        .try_collect()
        .map_err(|_| DkgError::DuplicateParticipants)?;

    macro_rules! run_with_faults {
        ($f:literal) => {{
            let info = Info::new::<MaxFaults<$f>>(DKG_NAMESPACE, epoch, None, dealers, players)
                .map_err(|error| DkgError::Protocol(format!("{error:?}")))?;
            run_dkg_with_info(setup, epoch, &identities, participants, info, rng)
        }};
    }

    match max_faults {
        0 => run_with_faults!(0),
        1 => run_with_faults!(1),
        2 => run_with_faults!(2),
        3 => run_with_faults!(3),
        4 => run_with_faults!(4),
        5 => run_with_faults!(5),
        6 => run_with_faults!(6),
        7 => run_with_faults!(7),
        8 => run_with_faults!(8),
        9 => run_with_faults!(9),
        10 => run_with_faults!(10),
        11 => run_with_faults!(11),
        12 => run_with_faults!(12),
        13 => run_with_faults!(13),
        14 => run_with_faults!(14),
        15 => run_with_faults!(15),
        16 => run_with_faults!(16),
        17 => run_with_faults!(17),
        18 => run_with_faults!(18),
        19 => run_with_faults!(19),
        20 => run_with_faults!(20),
        21 => run_with_faults!(21),
        22 => run_with_faults!(22),
        23 => run_with_faults!(23),
        24 => run_with_faults!(24),
        25 => run_with_faults!(25),
        26 => run_with_faults!(26),
        27 => run_with_faults!(27),
        28 => run_with_faults!(28),
        29 => run_with_faults!(29),
        30 => run_with_faults!(30),
        31 => run_with_faults!(31),
        32 => run_with_faults!(32),
        33 => run_with_faults!(33),
        34 => run_with_faults!(34),
        35 => run_with_faults!(35),
        36 => run_with_faults!(36),
        37 => run_with_faults!(37),
        38 => run_with_faults!(38),
        39 => run_with_faults!(39),
        40 => run_with_faults!(40),
        41 => run_with_faults!(41),
        42 => run_with_faults!(42),
        43 => run_with_faults!(43),
        44 => run_with_faults!(44),
        45 => run_with_faults!(45),
        46 => run_with_faults!(46),
        47 => run_with_faults!(47),
        48 => run_with_faults!(48),
        49 => run_with_faults!(49),
        50 => run_with_faults!(50),
        51 => run_with_faults!(51),
        52 => run_with_faults!(52),
        53 => run_with_faults!(53),
        54 => run_with_faults!(54),
        55 => run_with_faults!(55),
        56 => run_with_faults!(56),
        57 => run_with_faults!(57),
        58 => run_with_faults!(58),
        59 => run_with_faults!(59),
        60 => run_with_faults!(60),
        61 => run_with_faults!(61),
        62 => run_with_faults!(62),
        63 => run_with_faults!(63),
        64 => run_with_faults!(64),
        _ => Err(DkgError::InvalidParticipantCount(n)),
    }
}

fn run_dkg_with_info(
    setup: &GoldenSetup,
    _epoch: u64,
    identities: &[PrivateKey],
    participants: &[ParticipantSpec],
    info: Info,
    rng: &mut impl CryptoRngCore,
) -> Result<DkgResult, DkgError> {
    let n = identities.len();
    let max_players = setup.max_players();
    let threads = std::thread::available_parallelism().unwrap_or(NonZeroUsize::MIN);
    let strategy = Rayon::new(threads)
        .map_err(|error| DkgError::Protocol(format!("parallel strategy: {error}")))?;

    // Every local identity acts as a dealer.
    let mut signed_logs: BTreeMap<PublicKey, Vec<u8>> = BTreeMap::new();
    for identity in identities {
        let signed = golden::deal(rng, &setup.setup, &info, identity, None, &strategy)
            .map_err(|error| DkgError::Protocol(format!("{error:?}")))?;
        let encoded = signed.encode().to_vec();
        let (dealer, _) = signed
            .identify(&info)
            .ok_or_else(|| DkgError::InvalidDealerLog("identity failed".into()))?;
        signed_logs.insert(dealer, encoded);
    }

    // Use all dealer logs. Golden needs at least `threshold` distinct dealer logs.
    let encoded_logs: Vec<Vec<u8>> = signed_logs.values().cloned().collect();
    let (logs, transcript_hash) = verify_logs(max_players, &info, encoded_logs)?;

    // Run `play` for every player and collect the per-participant share.
    let mut output: Option<Output<PublicKey>> = None;
    let mut shares = Vec::with_capacity(n);
    for (index, identity) in identities.iter().enumerate() {
        let (player_output, share) =
            golden::play(rng, &setup.setup, &info, logs.clone(), identity, &strategy)
                .map_err(|error| DkgError::Protocol(format!("{error:?}")))?;
        if let Some(existing) = &output {
            if existing.encode().as_ref() != player_output.encode().as_ref() {
                return Err(DkgError::Protocol("mismatched player outputs".into()));
            }
        } else {
            output = Some(player_output);
        }
        let participant_id = participants[index].id.clone();
        shares.push((participant_id, share));
    }

    let output = output.expect("at least one player produced output");
    let public = output.public();
    Ok(DkgResult {
        public_output: output.clone(),
        public_output_bytes: output.encode().to_vec(),
        public_key: public.public().clone(),
        transcript_hash,
        shares,
    })
}

/// Produce a single threshold KEM partial decapsulation using a stored share.
pub fn partial_decapsulation(
    share: &Share,
    output: &Output<PublicKey>,
    encapsulation: &[u8],
    context: &[u8],
    rng: &mut impl CryptoRngCore,
) -> Result<crate::kem::DecapsulationShare, crate::kem::KemError> {
    let verification_share = output
        .public()
        .partial_public(share.index)
        .map_err(|_| crate::kem::KemError::InvalidEncoding)?;
    crate::kem::partial_decapsulation(share, &verification_share, encapsulation, context, rng)
}

fn verify_logs(
    max_players: NonZeroU32,
    info: &Info,
    encoded_logs: Vec<Vec<u8>>,
) -> Result<(BTreeMap<PublicKey, DealerLog>, [u8; 32]), DkgError> {
    let cfg = (max_players, ModeVersion::v0());
    let mut logs = BTreeMap::new();
    let mut signed_logs = BTreeMap::new();
    for encoded in encoded_logs {
        let mut bytes = encoded.as_slice();
        let signed = SignedDealerLog::read_cfg(&mut bytes, &cfg)
            .map_err(|error| DkgError::InvalidDealerLog(error.to_string()))?;
        if !bytes.is_empty() {
            return Err(DkgError::InvalidDealerLog("trailing bytes".into()));
        }
        let (dealer, log) = signed
            .identify(info)
            .ok_or_else(|| DkgError::InvalidDealerLog("identity failed".into()))?;
        if logs.insert(dealer.clone(), log).is_some()
            || signed_logs.insert(dealer, encoded).is_some()
        {
            return Err(DkgError::InvalidDealerLog("duplicate dealer".into()));
        }
    }

    let mut transcript = Sha256::new();
    transcript.update(info.summary().as_ref());
    for encoded in signed_logs.values() {
        transcript.update((encoded.len() as u64).to_be_bytes());
        transcript.update(encoded);
    }
    Ok((logs, transcript.finalize().into()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand_chacha::{rand_core::SeedableRng, ChaCha20Rng};

    #[test]
    fn dkg_2_of_3_produces_matching_output() {
        let mut rng = ChaCha20Rng::from_seed([42u8; 32]);
        let setup = GoldenSetup::generate(NonZeroU32::new(3).unwrap());
        let participants = vec![
            ParticipantSpec {
                id: "creator".into(),
                public_key: base64::encode("creator-key"),
            },
            ParticipantSpec {
                id: "mod-a".into(),
                public_key: base64::encode("mod-a-key"),
            },
            ParticipantSpec {
                id: "mod-b".into(),
                public_key: base64::encode("mod-b-key"),
            },
        ];
        let result = run_dkg(&setup, 1, &participants, 2, None, &mut rng).unwrap();
        assert_eq!(result.shares.len(), 3);
        assert!(!result.public_output_bytes.is_empty());
    }
}
